### ISSUE TITLE
電子処方箋のFHIR記述仕様書案との内容比較

### ISSUE THREAD

**Issue by hosanai** [HealthDataWorks/fhir-ig-jp-rezept-medication#4]
下記で関連するFHIR仕様が公開されています。本実装ガイドとの内容比較が必要
https://std.jpfhir.jp/
・電⼦処⽅箋 HL7® FHIR®記述仕様書案　　2021.3.29版

**Comment by ns0602yk** [comment]
電子処方箋と本実装ガイドのリソースの構造の比較結果を示します。

|差異があるリソース|要素|電子処方箋|調剤レセプト|
|---|---|---|---|
|Patient|identifier|医療機関ごとのIDを使用する|被保険者記号、被保険者番号を指定|
|Patient|name|漢字氏名、かな氏名の区別を、拡張で定義|漢字氏名をofficial、かな氏名をusualで区別|
|Coverage|extention|被保険者記号、被保険者番号を拡張で設定|extentionは使用しない(被保険者記号、被保険者番号はidentifierで指定)|
|Coverage|identifier|指定無し|被保険者記号、被保険者番号を指定|
|Coverage|costToBeneficiary|自己負担率を指定(任意)|指定無し|
|Organization|extention|都道府県番号(2桁)、点数表番号(1桁)、保健医療機関番号(7桁)をそれぞれ別のextentionで指定|extentionは使用しない(都道府県番号(2桁)、点数表番号(1桁)、保健医療機関番号(7桁)はidentifierで指定)|
|Organization|identifier|extentionの3つの番号を結合した10桁の番号を指定|都道府県番号(2桁)、点数表番号(1桁)、保健医療機関番号(7桁)をそれぞれ別のidentifierで指定|

**Comment by hosanai** [comment]
ありがとうございます。大きな差異がなく一安心ですね。extentionの使い方(≒identifierの使い方)について、考え方の違いがわかりましたが、電子処方箋はファイナル・ドラフトというステータスなので基本従う形での対応を進める方向でどうでしょうか？
一点、Patientのidentifierは、将来性を考慮するとマイナンバーを採用するのがベストだと思うのですが、医療機関での普及次第なところもありますが、被保険者記号・番号を使わず医療機関ごとのIDを使用は気になります。被保険者記号・番号はCoverageにあるから、ここは、マイナンバー普及までのつなぎということなのですかね？

**Comment by hosanai** [comment]
上記対応の場合、他のレセプト系実装ガイドの修正も必要となりますね

**Comment by ns0602yk** [comment]
本実装ガイドで検出した電子処方箋との差異を吸収し、電子処方箋に従った構造に修正しました。
あわせて、他のレセプト系実装ガイドについても修正しています。
